apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: java-consumer
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: java-consumer
  targetCPUUtilizationPercentage: 50
