apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: html-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: html-frontend
    spec:
      containers:
      - name: html-frontend
        image: html-frontend:1.0
        ports:
        - containerPort: 80
