apiVersion: v1
kind: Service
metadata:
  labels:
    app: html-frontend
  name: html-frontend
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: html-frontend
  sessionAffinity: None
  type: NodePort 
