apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: html-frontend
  name: html-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: html-frontend
  template:
    metadata:
      labels:
        run: html-frontend
    spec:
      containers:
      - image: dalealleshouse/html-frontend:1.0
        name: html-frontend
        env:
          - name: STATUS_HOST
            value: k8-master:31111
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz.html
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 2
        readinessProbe:
          httpGet:
            path: /healthz.html
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 2
