apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: java-consumer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: java-consumer
    spec:
      containers:
      - name: java-consumer
        image: java-consumer:1.0
