apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ruby-producer
  app: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
    - name: ruby-producer
      image: ruby-producer:1.0
      ports:
