apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: status-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: status-api
    spec:
      containers:
      - name: status-api
        image: status-api:1.0
        ports:
        - containerPort: 5000
