apiVersion: v1
kind: Service
metadata:
  labels:
    run: status-api
  name: status-api
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    run: status-api
  type: LoadBalancer
